### ISSUE TITLE
Name with special chars: Bad request (Error 400)

### ISSUE THREAD

**Issue by cottton** [netresearch/dhl-sdk-api-bcs-returns#5]
Receiving `Bad request (Error 400)` (and nothing more) from DHL if the name contains special chars like `à`.

Note: the source of the name string was in my case another api.

When i tried to copy and past the name it worked. Seems to be an encoding problem.

Im posting this because the DHL API does not mention anything about that.

You only get  `400 | Fehlerhafter Aufruf(Bad Request). | Syntax des Aufrufs prüfen.` from the documentation.

**Where:** at the shipper address name: 

    $requestBuilder->setShipperAddress(
        $name = 'Adrià Fernández', // <---------------------
        $countryCode = 'DEU',
        $postalCode = '53113',
        $city = 'Bonn',
        $streetName = 'Sträßchensweg',
        $streetNumber = '2'
    );

I fixed this using `$name = utf8_encode($name);` before sending it to DHL.
_But this is more like a quick fix, since the label then prints `Ã`._

**Comment by mam08ixo** [comment]
Thank you for your comment. How can we help?

**Comment by ngolatka** [comment]
I can't confirm this problem:

![image](https://user-images.githubusercontent.com/7393538/140943887-12513d6d-88f7-4c60-b60b-1c145f52a516.png)

**Comment by cottton** [comment]
> Thank you for your comment. How can we help?

You COULD add a solution to solve the encoding problem before DHL gets the name string.
But as i said:

> Im posting this because the DHL API does not mention anything about that.

So somebody may gets the same (kind of useless) error message from DHL
and then can find here one possible case causing this.

**Comment by mam08ixo** [comment]
If I understand you correctly, there is an issue with the data source that is not solved by converting to UTF-8. Since we are not the owner of your data source, I am afraid we cannot do anything about it.

The _Bad Request_ error enabled you to track down the root cause in the request, which is great.
We are not the API providers, so we cannot enhance the response / error message.

I kindly suggest you fix the issue at the source, the input data.
This issue will remain visible for others who may encounter encoding problems, thank you.
